#Default port is 8761 server:
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  #Uncomment when working in a development mode.
  #server:
    #waitTimeInMsWhenSyncEmpty: 5

---
spring:
  profiles: developer
server:
  port: 8761

---
spring:
  profiles: staging
server:
  port: ${PORT}